# Generated by Django 4.1.2 on 2023-07-14 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0002_remove_asker_body_remove_asker_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='askerbody',
            name='asker',
        ),
        migrations.RemoveField(
            model_name='botai',
            name='user',
        ),
        migrations.RemoveField(
            model_name='botbody',
            name='bot',
        ),
        migrations.DeleteModel(
            name='Asker',
        ),
        migrations.DeleteModel(
            name='Askerbody',
        ),
        migrations.DeleteModel(
            name='BotAi',
        ),
        migrations.DeleteModel(
            name='Botbody',
        ),
    ]
